// Date: 12/1/2014 8:04:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.minercraftstyle.labeledredstone.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelLabeledLever extends ModelBase
{
    public ModelRenderer leverBase;
    public ModelRenderer lever;
    public ModelRenderer postRight;
    public ModelRenderer postLeft;
    public ModelRenderer signBoard;
  
    public ModelLabeledLever()
    {
        leverBase = new ModelRenderer(this, 0, 0);
        leverBase.addBox(-3F, -2F, -4F, 6, 3, 8);
        lever = new ModelRenderer(this, 0, 0);
        lever.addBox(-1F, -7F, -1F, 2, 6, 2);

        postRight = new ModelRenderer(this, 0, 0);
        postRight.addBox(10F, -13F, -1F, 2, 14, 2);
        postLeft = new ModelRenderer(this, 0, 0);
        postLeft.addBox(-12F, -13F, -1F, 2, 14, 2);
        signBoard = new ModelRenderer(this, 0, 0);
        signBoard.addBox(-12F, -25F, -1F, 24, 12, 2);
    }

    public void renderLabeledLever()
    {
        this.leverBase.render(0.0F);
        this.lever.render(0.0F);
        this.signBoard.render(0.0625F);
        this.postLeft.render(0.0625F);
        this.postRight.render(0.0625F);
    }
}
