// Date: 12/1/2014 8:04:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.minercraftstyle.labeledredstone.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelLabeledRedstone extends ModelBase
{
    public ModelRenderer postRight;
    public ModelRenderer postLeft;
    public ModelRenderer signBoard;
  
    public ModelLabeledRedstone()
    {
        postRight = new ModelRenderer(this, 0, 14);
        postRight.addBox(10F, -2F, -1F, 2, 14, 2);
        postLeft = new ModelRenderer(this, 0, 14);
        postLeft.addBox(-12F, -2F, -1F, 2, 14, 2);
        signBoard = new ModelRenderer(this, 0, 0);
        signBoard.addBox(-12.0F, -14.0F, -1.0F, 24, 12, 2, 0.0F);
    }

    public void renderLabeledRedstone()
    {
        this.signBoard.render(0.0625F);
        this.postLeft.render(0.0625F);
        this.postRight.render(0.0625F);
    }
}
